'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace ProductConfigurator.Entity

    Partial Public Class SysproEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=SysproEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property QotDetails() As DbSet(Of QotDetail)
        Public Overridable Property QotMasters() As DbSet(Of QotMaster)
        Public Overridable Property InvWarehouses() As DbSet(Of InvWarehouse)
    
    End Class

End Namespace
