'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductConfig
    Public Property ConfigID As Integer
    Public Property Quote As String
    Public Property Line As Nullable(Of Integer)
    Public Property StockCode As String
    Public Property CostPrice As Nullable(Of Decimal)
    Public Property MarkUp As Nullable(Of Decimal)
    Public Property SellPrice As Nullable(Of Decimal)

End Class
