'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QotDetail
    Public Property Quote As String
    Public Property QuoteVersion As Decimal
    Public Property Line As Decimal
    Public Property LineType As String
    Public Property DefaultEntry As Decimal
    Public Property ProductClass As String
    Public Property TaxCode As String
    Public Property FedSalesTax As String
    Public Property MStockCode As String
    Public Property MDescription As String
    Public Property MWarehouse As String
    Public Property MUom As String
    Public Property MDecimals As Decimal
    Public Property MLineShipDate As Nullable(Of Date)
    Public Property MCusStockCode As String
    Public Property MCusRetailPrice As Decimal
    Public Property MMass As Decimal
    Public Property MVolume As Decimal
    Public Property MUserField1 As String
    Public Property Version As String
    Public Property Release As String
    Public Property SalesOrderLine As Decimal
    Public Property MBomFlag As String
    Public Property MParentKitType As String
    Public Property MQtyPer As Decimal
    Public Property MScrapPercentage As Decimal
    Public Property MPrintComponent As String
    Public Property MComponentSeq As String
    Public Property MOptionalFlag As String
    Public Property NComment As String
    Public Property NCommentFromLin As Decimal
    Public Property NCommentType As String
    Public Property NCommentTextTyp As String
    Public Property NSrvIncTotal As String
    Public Property NSrvSummary As String
    Public Property NSrvChargeType As String
    Public Property NSrvParentLine As Decimal
    Public Property NSrvQtyFactor As Decimal
    Public Property NSrvApplyFactor As String
    Public Property NSrvDecimalRnd As Decimal
    Public Property NSrvDecRndFlag As String
    Public Property NSrvMinValue As Decimal
    Public Property NSrvMaxValue As Decimal
    Public Property NSrvMulDiv As String
    Public Property NPrtOnInv As String
    Public Property NPrtOnDel As String
    Public Property NPrtOnAck As String
    Public Property NPrtOnQuote As String
    Public Property NCommentFlag1 As Decimal
    Public Property NCommentFlag2 As Decimal
    Public Property NCommentFlag3 As Decimal
    Public Property NCommentFlag4 As Decimal
    Public Property NCommentFlag5 As Decimal
    Public Property NCommentFlag6 As Decimal
    Public Property NCommentPoJob As String
    Public Property Estimate As String
    Public Property ConfirmedFlag As String
    Public Property NChargeCode As String
    Public Property Job As String
    Public Property MaterialAllocLine As String
    Public Property ScrapQuantity As Decimal
    Public Property FixedQtyPerFlag As String
    Public Property FixedQtyPer As Decimal
    Public Property ProductCode As String
    Public Property LibraryCode As String
    Public Property TimeStamp As Byte()

    Public Overridable Property QotMaster As QotMaster
    Public Overridable Property InvWarehouse As InvWarehouse

End Class
