'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QotMaster
    Public Property Quote As String
    Public Property QuoteVersion As Decimal
    Public Property QuoteStatus As String
    Public Property QuoteActive As String
    Public Property QuoteDescription As String
    Public Property Classification As String
    Public Property Customer As String
    Public Property CustomerName As String
    Public Property Contract As String
    Public Property ProfitBasis As String
    Public Property GlobalProfitPct As Decimal
    Public Property LabProfitBasis As String
    Public Property LabourProfitPct As Decimal
    Public Property MatProfitBasis As String
    Public Property MatProfitPct As Decimal
    Public Property ProbabilityFlag As Decimal
    Public Property HierarchyQuote As String
    Public Property DateEnquiry As Nullable(Of Date)
    Public Property DateFollowUp As Nullable(Of Date)
    Public Property DateTenderReq As Nullable(Of Date)
    Public Property DatePrinted As Nullable(Of Date)
    Public Property ExpiryDate As Nullable(Of Date)
    Public Property DateConfirmRej As Nullable(Of Date)
    Public Property DateDeliveryReq As Nullable(Of Date)
    Public Property DummySalesOrder As String
    Public Property DummySoUpdated As String
    Public Property ImplosionCtlNum As Decimal
    Public Property ContPriceAllow As String
    Public Property BuyingGroup1 As String
    Public Property BuyingGroup2 As String
    Public Property BuyingGroup3 As String
    Public Property BuyingGroup4 As String
    Public Property BuyingGroup5 As String
    Public Property InvDiscCode As String
    Public Property LineDiscCode As String
    Public Property DiscountCode As String
    Public Property PriceCategoryTable As String
    Public Property ApplyOrderDisc As String
    Public Property ApplyLineDisc As String
    Public Property NextNonStockNum As Decimal
    Public Property ReasonCode As String
    Public Property ReasonDesc As String
    Public Property IssueNum As Decimal
    Public Property PreviousStatus As String
    Public Property OfferDesc1 As String
    Public Property OfferDesc2 As String
    Public Property OfferDesc3 As String
    Public Property OfferDesc4 As String
    Public Property OfferDesc5 As String
    Public Property OfferDesc6 As String
    Public Property OfferPrt1 As String
    Public Property OfferPrt2 As String
    Public Property OfferPrt3 As String
    Public Property OfferPrt4 As String
    Public Property OfferPrt5 As String
    Public Property OfferPrt6 As String
    Public Property Contact As String
    Public Property SalesOrder As String
    Public Property Fax As String
    Public Property Telephone As String
    Public Property NonStockPrefix As String
    Public Property ChangeDate As Nullable(Of Date)
    Public Property ChangeTime As Decimal
    Public Property [Operator] As String
    Public Property TimeStamp As Byte()

    Public Overridable Property QotDetails As ICollection(Of QotDetail) = New HashSet(Of QotDetail)

End Class
